We now use a different approach to avoid blocking the post installation script if the agent can't be restarted because of an unexisting config file. It uses the || operator and displays a notice message in case of failure.

diff --git a/package-scripts/datadog-agent/postinst b/package-scripts/datadog-agent/postinst
--- a/package-scripts/datadog-agent/postinst
+++ b/package-scripts/datadog-agent/postinst
@@ -57,14 +57,12 @@ if which chkconfig >/dev/null 2>&1; then
   chkconfig --add datadog-agent
 fi
 
-set +e
+MISSING_CONF_MSG="\033[34m\n* No /etc/dd-agent/datadog.conf file has been found.\033[0m"
 if which invoke-rc.d >/dev/null 2>&1; then
-    invoke-rc.d datadog-agent restart
+    invoke-rc.d datadog-agent restart || echo "$MISSING_CONF_MSG"
 else
-    /etc/init.d/datadog-agent restart
+    /etc/init.d/datadog-agent restart || echo "$MISSING_CONF_MSG"
 fi
-set -e
-
 RETVAL=$?
 if [ $RETVAL -ne 0 ]; then
     if [ $RETVAL -eq 3 ]; then
