[osx] Migration to omnibus 4
The project has been made compliant with the OSX Omnibus build. Builds
are now on the same branch for OSX and Linux and can be triggered using
the same set of commands. Please have a look at the README.md file in
order to make sure you have all the requirements installed on your Mac.

diff --git a/package-scripts/datadog-agent/postinst b/package-scripts/datadog-agent/postinst
--- a/package-scripts/datadog-agent/postinst
+++ b/package-scripts/datadog-agent/postinst
@@ -1,90 +1,186 @@
 #!/bin/sh
 
-CONFIG_DIR=/etc/dd-agent
+INSTALL_DIR=/opt/datadog-agent
 LOG_DIR=/var/log/datadog
 RUN_DIR=/opt/datadog-agent/run
 
-LINUX_DISTRIBUTION=$(grep -Eo "(Debian|Ubuntu|RedHat|CentOS|openSUSE|Amazon)" /etc/issue)
+DISTRIBUTION=$(grep -Eo "(Debian|Ubuntu|RedHat|CentOS|openSUSE|Amazon)" /etc/issue 2>/dev/null || uname -s)
 
 error_exit()
 {
-    echo "${PROGNAME}: ${1:-"Unknown Error"}" 1>&2
-    exit 1
+  echo "${PROGNAME}: ${1:-"Unknown Error"}" 1>&2
+  exit 1
 }
 
 mkdir -p ${LOG_DIR} || error_exit "Cannot create ${LOG_DIR}!"
 
 # If we are inside the Docker container, do nothing
 if [ -n "$DOCKER_DD_AGENT" ]; then
-    echo "Installation from docker-dd-agent, nothing to do in postinst"
-    exit 0
+  echo "Installation from docker-dd-agent, nothing to do in postinst"
+  exit 0
 fi
 
-# Since we now package our own supervisor config, we no longer want
-# the old config to be loaded. Since supervisor automatically loads
-# configs in conf.d, we have to delete the old config file.
-if [ -f /etc/supervisor/conf.d/ddagent.conf ]; then
-    echo "Removing old configuration from system supervisord"
-    rm /etc/supervisor/conf.d/ddagent.conf
-fi
+# Linux installation
+if ["$DISTRIBUTION" != "Darwin"]; then
+  # Linus specific variables
+  CONFIG_DIR=/etc/dd-agent
 
-if [ -f /etc/debian_version ] || [ "$LINUX_DISTRIBUTION" == "Debian" ] || [ "$LINUX_DISTRIBUTION" == "Ubuntu" ]; then
-    set -e
-    case "$1" in
-        configure)
-            update-rc.d datadog-agent defaults
-            update-rc.d datadog-agent enable >/dev/null 2>&1
-            adduser --system dd-agent --disabled-login --shell /bin/sh --no-create-home --quiet
-            usermod -d /opt/datadog-agent dd-agent
-            set +e
-        ;;
-        abort-upgrade|abort-remove|abort-deconfigure)
-        ;;
+  # Since we now package our own supervisor config, we no longer want
+  # the old config to be loaded. Since supervisor automatically loads
+  # configs in conf.d, we have to delete the old config file.
+  if [ -f /etc/supervisor/conf.d/ddagent.conf ]; then
+      echo "Removing old configuration from system supervisord"
+      rm /etc/supervisor/conf.d/ddagent.conf
+  fi
 
-        *)
-        ;;
-    esac
-    #DEBHELPER#
-fi
+  if [ -f /etc/debian_version ] || [ "$DISTRIBUTION" == "Debian" ] || [ "$DISTRIBUTION" == "Ubuntu" ]; then
+      set -e
+      case "$1" in
+          configure)
+              update-rc.d datadog-agent defaults
+              update-rc.d datadog-agent enable >/dev/null 2>&1
+              adduser --system dd-agent --disabled-login --shell /bin/sh --no-create-home --quiet
+              usermod -d /opt/datadog-agent dd-agent
+              set +e
+          ;;
+          abort-upgrade|abort-remove|abort-deconfigure)
+          ;;
 
-# Set proper rights to the dd-agent user
-chown -R dd-agent:root ${CONFIG_DIR}
-chown -R dd-agent:root ${LOG_DIR}
-chown root:root /etc/init.d/datadog-agent
-chown -R root:root /opt/datadog-agent
-chown -R dd-agent:root ${RUN_DIR}
+          *)
+          ;;
+      esac
+      #DEBHELPER#
+  fi
 
-if command -v chkconfig >/dev/null 2>&1; then
-    chkconfig --add datadog-agent
-fi
+  # Set proper rights to the dd-agent user
+  chown -R dd-agent:root ${CONFIG_DIR}
+  chown -R dd-agent:root ${LOG_DIR}
+  chown root:root /etc/init.d/datadog-agent
+  chown -R root:root /opt/datadog-agent
 
-# The configcheck call will return zero if the config is valid, which means we
-# can restart the agent without taking the risk to trigger an error in the
-# postinst script . If the config file doesn't exist (RETVAL=3), the user is
-# probably using the packaged install script so let's consider the postinst
-# script did its job and exist zero, otherwise, if the file exists but it's
-# wrong we have to return a non zero exit status so that the system
-# (and the user) are notified the installation went wrong.
-/etc/init.d/datadog-agent configcheck
-RETVAL=$?
-if [ $RETVAL -eq 0 ]; then
-    echo "(Re)starting datadog-agent now..."
-    if command -v invoke-rc.d >/dev/null 2>&1; then
-        invoke-rc.d datadog-agent restart
-    else
-        /etc/init.d/datadog-agent restart
-    fi
-fi
+  if command -v chkconfig >/dev/null 2>&1; then
+      chkconfig --add datadog-agent
+  fi
 
-if [ $RETVAL -ne 0 ]; then
-    if [ $RETVAL -eq 3 ]; then
-        # No datadog.conf file is present. The user is probably following
-        # the step-by-step instructions (or using the packaged install script)
-        # and will add the config file next.
-        exit 0
-    else
-        exit $RETVAL
-    fi
+  # The configcheck call will return zero if the config is valid, which means we
+  # can restart the agent without taking the risk to trigger an error in the
+  # postinst script . If the config file doesn't exist (RETVAL=3), the user is
+  # probably using the source install script so let's consider the postinst script
+  # did its job and exist zero, otherwise, if the file exists but it's wrong we
+  # have to return a non zero exit status so that the system (and the user) are
+  # notified the installation went wrong.
+  /etc/init.d/datadog-agent configcheck
+  RETVAL=$?
+  if [ $RETVAL -eq 0 ]; then
+      echo "(Re)starting datadog-agent now..."
+      if command -v invoke-rc.d >/dev/null 2>&1; then
+          invoke-rc.d datadog-agent restart
+      else
+          /etc/init.d/datadog-agent restart
+      fi
+  fi
+
+  if [ $RETVAL -ne 0 ]; then
+      if [ $RETVAL -eq 3 ]; then
+          # No datadog.conf file is present. The user is probably following
+          # the step-by-step instructions and will add the config file next.
+          exit 0
+      else
+          exit $RETVAL
+      fi
+  fi
+# OSX installation
+elif [ $DISTRIBUTION = "Darwin"]; then
+  # OSX specific variables
+  OPT_APP_DIR="$INSTALL_DIR/Datadog Agent.app"
+  APP_DIRECTORY="/Applications/Datadog Agent.app"
+  APP_CONF_DIR="$APP_DIRECTORY/Contents/Resources"
+  RUN_DIR="$APP_CONF_DIR/run"
+  LOG_FILE="$LOG_DIR/postinstall.log"
+
+  # Let's log the standard outputs of this script
+  exec > $LOG_FILE 2>&1
+
+  # Determine current user if he is using the Graphical installer
+  INSTALL_USER=$(ps aux | grep "CoreServices/Installer" | grep -v grep | awk '{print $1;}')
+
+  # Otherwise, we hope he is using the install script and try to this user
+  # If it fails, no choice but to use root :'(
+  if [ -z "$INSTALL_USER" ] || [ "$INSTALL_USER" == "root" ]; then
+    SCRIPT_INSTALL="yes"
+    INSTALL_USER=`cat /tmp/datadog-install-user || echo 'root'`
+    rm /tmp/datadog-install-user || true
+  fi
+
+  # Reinstall is really different:
+  # the app is extracted directly where the old version is
+  # So we only try to install if the app is in /opt
+  if [ -e "$OPT_APP_DIR" ]; then
+    # Prepare log dir
+    chown -R $INSTALL_USER:admin $LOG_DIR
+    chmod 755 $LOG_DIR
+
+    # Installing the app
+    rm -rf $APP_DIRECTORY
+    mv $INSTALL_DIR/Datadog\ Agent.app /Applications
+  fi
+
+  if [ "$INSTALL_USER" == "root" ]; then
+    echo 'INSTALL_USER is set to root, Datadog Agent app has been installed'
+    echo 'but is not configured. Running Datadog Agent as root is not advised!'
+    exit 1
+  fi
+
+  # Set the run directory for supervisord
+  mkdir -p "$RUN_DIR"
+  chown -R $INSTALL_USER:admin "$RUN_DIR"
+  chmod 755 "$RUN_DIR"
+
+  sed "s|USER_NAME|$INSTALL_USER|" "$APP_CONF_DIR/com.datadoghq.Agent.plist.example" > "$APP_CONF_DIR/com.datadoghq.Agent.plist"
+
+  # Copying existing conf is one exists
+  if [ -e "/tmp/datadog.conf" ]; then
+    mv -f /tmp/datadog.conf "$APP_CONF_DIR/"
+    mv -f /tmp/conf.d/* "$APP_CONF_DIR/conf.d"
+    cp -n /tmp/checks.d/* "$APP_CONF_DIR/checks.d"
+    rm -rf /tmp/datadog.conf /tmp/conf.d /tmp/checks.d
+  # Or copying default
+  else
+    sed -E 's/^api_key:$/api_key: APIKEY/' "$APP_CONF_DIR/datadog.conf.example" > "$APP_CONF_DIR/datadog.conf"
+  fi
+
+  # Correct rights
+  chown $INSTALL_USER:admin "$APP_CONF_DIR/datadog.conf"
+  chown -R $INSTALL_USER:admin "$APP_CONF_DIR/conf.d" "$APP_CONF_DIR/checks.d"
+
+  # `datadog-agent` command line
+  mkdir -p /usr/local/bin
+  ln -s "$APP_CONF_DIR/../MacOS/datadog-agent" /usr/local/bin/datadog-agent
+
+  # Link for conf files (let's ease the user's life)
+  USER_HOME=`sudo -Hu $INSTALL_USER sh -c 'echo $HOME'`
+  sudo -Hu $INSTALL_USER mkdir -p "$USER_HOME/.datadog-agent"
+  rm -f "$USER_HOME/.datadog-agent/conf.d" "$USER_HOME/.datadog-agent/datadog.conf" "$USER_HOME/.datadog-agent/checks.d"
+  sudo -Hu $INSTALL_USER ln -s "$APP_CONF_DIR/conf.d" "$USER_HOME/.datadog-agent/conf.d"
+  sudo -Hu $INSTALL_USER ln -s "$APP_CONF_DIR/datadog.conf" "$USER_HOME/.datadog-agent/datadog.conf"
+  sudo -Hu $INSTALL_USER ln -s "$APP_CONF_DIR/checks.d" "$USER_HOME/.datadog-agent/checks.d"
+
+  # Error if app not properly installed
+  if [ ! -e "$APP_CONF_DIR/datadog.conf" ]; then
+    exit 1
+  fi
+
+  # Start the app only if it's not a script install
+  if [ -z "$SCRIPT_INSTALL" ]; then
+    # Trick to get the right temp dir (for status pickles)
+    export TMPDIR=`sudo -u $INSTALL_USER getconf DARWIN_USER_TEMP_DIR`
+    sudo -Eu $INSTALL_USER open -a 'Datadog Agent.app'
+  fi
+  # And finally configure the app to be launched at login
+  sudo -u $INSTALL_USER osascript -e 'tell application "System Events" to delete every login item whose name is "Datadog Agent"'
+  # It uses the hardcoded path instead of $APP_DIRECTORY because
+  # osascript wants '' (bash doesn't interpolate $APP_DIRECTORY) and no ""
+  sudo -u $INSTALL_USER osascript -e 'tell application "System Events" to make login item at end with properties {path:"/Applications/Datadog Agent.app", name:"Datadog Agent", hidden:false}'
 fi
 
 exit 0
diff --git a/package-scripts/datadog-agent/preinst b/package-scripts/datadog-agent/preinst
--- a/package-scripts/datadog-agent/preinst
+++ b/package-scripts/datadog-agent/preinst
@@ -1,46 +1,88 @@
 #! /bin/sh
 
+INSTALL_DIR=/opt/datadog-agent
+LOG_DIR=/var/log/datad
+mkdir -p $LOG_DIR
+
 # Just in case there are leftovers from previous installation (we are now using our own
 # supervisord)
-KNOWN_DISTRIBUTION="(Debian|Ubuntu|RedHat|CentOS|openSUSE|Amazon)"
-LINUX_DISTRIBUTION=$(lsb_release -d 2>/dev/null | grep -Eo $KNOWN_DISTRIBUTION  || grep -Eo $KNOWN_DISTRIBUTION /etc/issue)
+KNOWN_LINUX_DISTRIBUTION="(Debian|Ubuntu|RedHat|CentOS|openSUSE|Amazon)"
+LINUX_DISTRIBUTION=$(lsb_release -d 2>/dev/null | grep -Eo $KNOWN_LINUX_DISTRIBUTION  || grep -Eo $KNOWN_DISTRIBUTION /etc/issue 2>/dev/null || uname -s)
 
-if [ -f /etc/debian_version ] || [ "$LINUX_DISTRIBUTION" == "Debian" ] || [ "$LINUX_DISTRIBUTION" == "Ubuntu" ]; then
-  set -e
-  if [ -f /etc/init.d/datadog-agent ]; then
-      if command -v invoke-rc.d >/dev/null 2>&1; then
-          invoke-rc.d datadog-agent stop || true
-      else
-          /etc/init.d/datadog-agent stop || true
+# Linux installation
+if [$DISTRIBUTION != "Darwin"]; then
+  if [ -f /etc/debian_version ] || [ "$DISTRIBUTION" == "Debian" ] || [ "$DISTRIBUTION" == "Ubuntu" ]; then
+    set -e
+    if [ -f /etc/init.d/datadog-agent ]; then
+        if command -v invoke-rc.d >/dev/null 2>&1; then
+            invoke-rc.d datadog-agent stop || true
+        else
+            /etc/init.d/datadog-agent stop || true
+        fi
+    fi
+
+    # Since we now package our own supervisor config, we no longer want
+    # the old config to be loaded. Since supervisor automatically loads
+    # configs in conf.d, we have to delete the old config file.
+    if [ -f /etc/supervisor/conf.d/ddagent.conf ]; then
+        echo "Removing old configuration from system supervisord"
+        rm /etc/supervisor/conf.d/ddagent.conf
+    fi
+
+    # Previous versions of dd-agent created this file but didn't do
+    # anything with it.
+    if [ -f /etc/dd-agent/supervisor_ddagent.conf ]; then
+        rm /etc/dd-agent/supervisor_ddagent.conf
+    fi
+
+    #DEBHELPER#
+
+  elif [ -f /etc/redhat-release ] || [ -f /etc/system-release ] || [ "$LINUX_DISTRIBUTION" == "RedHat" ] || [ "$LINUX_DISTRIBUTION" == "CentOS" ] || [ "$LINUX_DISTRIBUTION" == "openSUSE" ] || [ "$LINUX_DISTRIBUTION" == "Amazon" ]; then
+      getent group dd-agent >/dev/null || groupadd -r dd-agent
+      getent passwd dd-agent >/dev/null || \
+          useradd -r -M -g dd-agent -d /opt/datadog-agent -s /bin/sh \
+          -c "Datadog Agent" dd-agent
+
+      grep -q "datadog" /etc/supervisord.conf
+      if [ $? -eq 0 ]
+        then
+        echo -n "Removing old configuration from system supervisord"
+         if [ -x "/usr/bin/supervisorctl" ]; then
+              supervisorctl stop collector
+              supervisorctl stop forwarder
+         fi
+
+        /opt/datadog-agent/setup-supervisor.py /etc/dd-agent/supervisor.conf /etc/supervisord.conf remove
+        rm /opt/datadog-agent/setup-supervisor.py
       fi
+
+  else
+      echo "[ ${Red}FAILED ${RCol}]\tYour system is currently not supported by this script.";
+      exit 1;
   fi
+elif [$DISTRIBUTION = "Darwin"]; then
+    APP_CONF_DIR="/Applications/Datadog Agent.app/Contents/Resources"
 
-  # Since we now package our own supervisor config, we no longer want
-  # the old config to be loaded. Since supervisor automatically loads
-  # configs in conf.d, we have to delete the old config file.
-  if [ -f /etc/supervisor/conf.d/ddagent.conf ]; then
-      echo "Removing old configuration from system supervisord"
-      rm /etc/supervisor/conf.d/ddagent.conf
-  fi
+    LOG_FILE="$LOG_DIR/preinstall.log"
+    exec > $LOG_FILE 2>&1
 
-  # Previous versions of dd-agent created this file but didn't do
-  # anything with it.
-  if [ -f /etc/dd-agent/supervisor_ddagent.conf ]; then
-      rm /etc/dd-agent/supervisor_ddagent.conf
-  fi
+    if [ -e "$APP_CONF_DIR/datadog.conf" ]; then
+	  # Stop old version
+          "$APP_CONF_DIR/../MacOS/datadog-agent" stop || true
+          kill `ps aux | grep 'Datadog Agent.app' | grep -v grep  | cut -d ' ' -f 4` || true
 
-  #DEBHELPER#
+          # Save old conf
+          mkdir -p /tmp/conf.d
+          rm -rf /tmp/checks.d
+          rm -f /tmp/datadog.conf /tmp/conf.d/*
+	  cp -f "$APP_CONF_DIR/datadog.conf" /tmp
+	  cp -f "$APP_CONF_DIR/conf.d/"*.yaml /tmp/conf.d
+	  cp -fR "$APP_CONF_DIR/checks.d" /tmp/
+ 	fi
 
-elif [ -f /etc/redhat-release ] || [ -f /etc/system-release ] || [ "$LINUX_DISTRIBUTION" == "RedHat" ] || [ "$LINUX_DISTRIBUTION" == "CentOS" ] || [ "$LINUX_DISTRIBUTION" == "openSUSE" ] || [ "$LINUX_DISTRIBUTION" == "Amazon" ]; then
-    getent group dd-agent >/dev/null || groupadd -r dd-agent
-    getent passwd dd-agent >/dev/null || \
-        useradd -r -M -g dd-agent -d /opt/datadog-agent -s /bin/sh \
-        -c "Datadog Agent" dd-agent
-    # Stop the old agent before installing
-    /etc/init.d/datadog-agent stop || true
-else
-    echo "[ ${Red}FAILED ${RCol}]\tYour system is currently not supported by this script.";
-    exit 1;
+ 	# Clean before install
+    rm -rf $INSTALL_DIR
+    rm -f /usr/local/bin/datadog-agent
 fi
 
 # Delete .pyc files
