[osx] Split GUI and agent
This is a catchup with Quentin's changes on the OSX build (here's the
commit he made: https://github.com/DataDog/dd-agent-omnibus/commit/caae8869003afefa354abb61cfc747efbd8d1566#diff-204bd43b88bfd17fc7c160430a27547aR35)

And here's the original commit message :

See https://github.com/DataDog/dd-agent/pull/1361 for more
details about the agent.
Consequences for dd-agent-omnibus:
- software definition of `datadog-agent`:
  * ship `datadog-agent` command line tool in install_dir/bin
  * delete GUI-only packages after app creation
  * do not delete anymore install_dir/{agent,embedded}
  * create and fill install_dir/etc conf directory
- preinst script:
  * use new conf dir `/opt/datadog-agent/etc`
  * delete agent pyc files
- postinst script:
  * some more logs for easier debug (logs are only visible in
  /var/log/datadog/preinstall.log)
  * use new conf dir

diff --git a/package-scripts/datadog-agent/preinst b/package-scripts/datadog-agent/preinst
--- a/package-scripts/datadog-agent/preinst
+++ b/package-scripts/datadog-agent/preinst
@@ -14,19 +14,19 @@ if [$DISTRIBUTION != "Darwin"]; then
   if [ -f /etc/debian_version ] || [ "$DISTRIBUTION" == "Debian" ] || [ "$DISTRIBUTION" == "Ubuntu" ]; then
     set -e
     if [ -f /etc/init.d/datadog-agent ]; then
-        if command -v invoke-rc.d >/dev/null 2>&1; then
-            invoke-rc.d datadog-agent stop || true
-        else
-            /etc/init.d/datadog-agent stop || true
-        fi
+      if command -v invoke-rc.d >/dev/null 2>&1; then
+        invoke-rc.d datadog-agent stop || true
+      else
+        /etc/init.d/datadog-agent stop || true
+      fi
     fi
 
     # Since we now package our own supervisor config, we no longer want
     # the old config to be loaded. Since supervisor automatically loads
     # configs in conf.d, we have to delete the old config file.
     if [ -f /etc/supervisor/conf.d/ddagent.conf ]; then
-        echo "Removing old configuration from system supervisord"
-        rm /etc/supervisor/conf.d/ddagent.conf
+      echo "Removing old configuration from system supervisord"
+      rm /etc/supervisor/conf.d/ddagent.conf
     fi
 
     # Previous versions of dd-agent created this file but didn't do
@@ -38,62 +38,86 @@ if [$DISTRIBUTION != "Darwin"]; then
     #DEBHELPER#
 
   elif [ -f /etc/redhat-release ] || [ -f /etc/system-release ] || [ "$LINUX_DISTRIBUTION" == "RedHat" ] || [ "$LINUX_DISTRIBUTION" == "CentOS" ] || [ "$LINUX_DISTRIBUTION" == "openSUSE" ] || [ "$LINUX_DISTRIBUTION" == "Amazon" ]; then
-      getent group dd-agent >/dev/null || groupadd -r dd-agent
-      getent passwd dd-agent >/dev/null || \
-          useradd -r -M -g dd-agent -d /opt/datadog-agent -s /bin/sh \
-          -c "Datadog Agent" dd-agent
+    getent group dd-agent >/dev/null || groupadd -r dd-agent
+    getent passwd dd-agent >/dev/null || \
+      useradd -r -M -g dd-agent -d /opt/datadog-agent -s /bin/sh \
+        -c "Datadog Agent" dd-agent
 
-      grep -q "datadog" /etc/supervisord.conf
-      if [ $? -eq 0 ]
-        then
-        echo -n "Removing old configuration from system supervisord"
-         if [ -x "/usr/bin/supervisorctl" ]; then
-              supervisorctl stop collector
-              supervisorctl stop forwarder
-         fi
+    grep -q "datadog" /etc/supervisord.conf
+    if [ $? -eq 0 ]
+      then
+      echo -n "Removing old configuration from system supervisord"
+        if [ -x "/usr/bin/supervisorctl" ]; then
+          supervisorctl stop collector
+          supervisorctl stop forwarder
+        fi
 
-        /opt/datadog-agent/setup-supervisor.py /etc/dd-agent/supervisor.conf /etc/supervisord.conf remove
-        rm /opt/datadog-agent/setup-supervisor.py
-      fi
+      /opt/datadog-agent/setup-supervisor.py /etc/dd-agent/supervisor.conf /etc/supervisord.conf remove
+      rm /opt/datadog-agent/setup-supervisor.py
+    fi
 
   else
-      echo "[ ${Red}FAILED ${RCol}]\tYour system is currently not supported by this script.";
-      exit 1;
+    echo "[ ${Red}FAILED ${RCol}]\tYour system is currently not supported by this script.";
+    exit 1;
   fi
+
+  # Delete .pyc files
+  # FIXME: it shouldn't be done there, but only in prerm (see 6.6
+  # of https://www.debian.org/doc/debian-policy/ch-maintainerscripts.html)
+  # It is also here because version < 5.4 didn't delete .pyc,
+  # so we need to be sure to clean them here (if a file is deleted for instance)
+  find /opt/datadog-agent/agent -name '*.py[co]' -type f -delete || true
+
+  # FIXME: remove when CentOS5 support is dropped (03/31/2017) or when everybody
+  # has stopped using dd-agent 5.3 (and older versions ofc)
+  rm -f /opt/datadog-agent/agent/checks/utils.py
+
 elif [$DISTRIBUTION = "Darwin"]; then
-    APP_CONF_DIR="/Applications/Datadog Agent.app/Contents/Resources"
+  DD_COMMAND="/opt/datadog-agent/bin/datadog-agent"
+  CONF_DIR="$INSTALL_DIR/etc"
+  APP_DIR="/Applications/Datadog Agent.app"
 
-    LOG_FILE="$LOG_DIR/preinstall.log"
-    exec > $LOG_FILE 2>&1
+  LOG_FILE="$LOG_DIR/preinstall.log"
+  exec > $LOG_FILE 2>&1
 
-    if [ -e "$APP_CONF_DIR/datadog.conf" ]; then
-	  # Stop old version
-          "$APP_CONF_DIR/../MacOS/datadog-agent" stop || true
-          kill `ps aux | grep 'Datadog Agent.app' | grep -v grep  | cut -d ' ' -f 4` || true
+  if [ -e "$CONF_DIR/datadog.conf" ]; then
+    echo "# State at the beginning"
+    echo "## Agent version"
+    grep AGENT_VERSION $INSTALL_DIR/agent/config.py || echo "No config file"
+    echo "## $INSTALL_DIR"
+    ls -al $INSTALL_DIR || echo "No agent installed"
+    echo "## $APP_DIR/Contents/Resources"
+    ls -al "$APP_DIR/Contents/Resources" || echo "No app installed"
 
-          # Save old conf
-          mkdir -p /tmp/conf.d
-          rm -rf /tmp/checks.d
-          rm -f /tmp/datadog.conf /tmp/conf.d/*
-	  cp -f "$APP_CONF_DIR/datadog.conf" /tmp
-	  cp -f "$APP_CONF_DIR/conf.d/"*.yaml /tmp/conf.d
-	  cp -fR "$APP_CONF_DIR/checks.d" /tmp/
- 	fi
+    echo '# Stop old agent'
+    $DD_COMMAND stop || true
+    kill `ps aux | grep 'Datadog Agent.app' | grep -v grep  | cut -d ' ' -f 4` || true
 
- 	# Clean before install
-    rm -rf $INSTALL_DIR
-    rm -f /usr/local/bin/datadog-agent
+    echo '# Stop old GUI'okill `ps aux | grep 'Datadog Agent.app' | grep -v grep | awk '{ print $2 }'` || true
+
+    # Save old conf
+    mkdir -vp /tmp/{conf,checks}.d
+    rm -rvf /tmp/{checks,conf}.d/* /tmp/datadog.conf
+    cp -vf $CONF_DIR/datadog.conf /tmp
+    cp -vf $CONF_DIR/conf.d/*.yaml /tmp/conf.d
+    cp -vfR $CONF_DIR/checks.d/* /tmp/checks.d
+  fi
+
+  echo '# Deleting old datadog-agent link'
+  rm -vf /usr/local/bin/datadog-agent
+
+  echo '# Deleting .pyc files'
+  find /opt/datadog-agent/agent -name '*.py[co]' -type f -delete || true
+
+  # Debriefing time
+  echo "# State at the end"
+  echo "## Agent version"
+  grep AGENT_VERSION $INSTALL_DIR/agent/config.py || echo "No config file"
+  echo "## $INSTALL_DIR"
+  ls -al $INSTALL_DIR || echo "No agent installed"
+  echo "## $APP_DIR/Contents/Resources"
+  ls -al "$APP_DIR/Contents/Resources" || echo "No app installed"
 fi
 
-# Delete .pyc files
-# FIXME: it shouldn't be done there, but only in prerm (see 6.6
-# of https://www.debian.org/doc/debian-policy/ch-maintainerscripts.html)
-# It is also here because version < 5.4 didn't delete .pyc,
-# so we need to be sure to clean them here (if a file is deleted for instance)
-find /opt/datadog-agent/agent -name '*.py[co]' -type f -delete || true
-
-# FIXME: remove when CentOS5 support is dropped (03/31/2017) or when everybody
-# has stopped using dd-agent 5.3 (and older versions ofc)
-rm -f /opt/datadog-agent/agent/checks/utils.py
 
 exit 0
